### ISSUE TITLE
Non funziona

### ISSUE THREAD

**Issue by andreatosato** [italia/fatturapa-webapp#6]
Ciao ragazzi, ho provato questa applicazione ma non capisco se è completa o meno.
Non c'è un readme che spiega lo scopo del progetto.
L'ho deployato qui: http://fatturapatest.azurewebsites.net ma, oltre alla pagina principale, non c'è nulla.
Sotto https non va.
Sto sbagliando qualcosa?

**Comment by simevo** [comment]
Ciao ! grazie per l'interesse. In effetti l'attività su questo repo si è arenata.

L'idea era che fatturapa-webapp diventasse una webapp orientata all'utente finale, con funzioni di creazione / archiviazione / ricerca di fatture, nonché di interfacciamento col canale SDIcoop. Queste ultime dovrebbero saranno fornite da una libreria core *fatturapa-php-sdk*.

Le nostre energie al momento sono assorbite da quest'ultima, anzi per essere più precisi:
- del sistema di test [fattuarapa-testsdi](https://github.com/italia/fatturapa-testsdi) che include la libreria core e pure un implementazione indipendente del Sistema di Interscambio (SDI)
- della relativa User Interface di controllo [fattuarapa-testui](https://github.com/simevo/fatturapa-testui) utile per pilotare i tests.

Ti inviterei ad unirti al canale #fatturapa su https://slack.developers.italia.it/ per discutere di questi temi, putroppo al momento il link per l'invito è rotto (vedi https://github.com/italia/fatturapa-php-sdk/issues/10#issuecomment-424491587).. ti segnalo qui quando riprende a funzionare !

**Comment by simevo** [comment]
Ciao @andreatosato il link su https://slack.developers.italia.it/ è tornato online, rinnovo l'invito a unirti al canale #fatturapa !

**Comment by andreatosato** [comment]
@simevo grazie
