### ISSUE TITLE
Info progetto.

### ISSUE THREAD

**Issue by felix1** [italia/fatturapa-webapp#7]
Salve, il progetto è completato oppure è in fase di sviluppo?

Grazie in anticipo per la risposta.

**Comment by simevo** [comment]
Ciao al momento lo sviluppo qui è in pausa, ci siamo concentrati sul sistema di interscambio di test: https://github.com/italia/fatturapa-testsdi

Se sei interessato a questi temi ti invito ad unirti al canale #fatturapa su https://slack.developers.italia.it/
